/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as mainHomeLayoutImport } from './routes/(main)/_homeLayout'
import { Route as mainHomeLayoutIndexImport } from './routes/(main)/_homeLayout/index'
import { Route as dashboardDDashboardLayoutImport } from './routes/(dashboard)/d/_dashboardLayout'
import { Route as mainHomeLayoutWishlistIndexImport } from './routes/(main)/_homeLayout/wishlist/index'
import { Route as dashboardDPartnersIndexImport } from './routes/(dashboard)/d/partners/index'
import { Route as mainHomeLayoutprofileProfileLayoutImport } from './routes/(main)/_homeLayout/(profile)/_profileLayout'
import { Route as dashboardDDashboardLayoutProductsIndexImport } from './routes/(dashboard)/d/_dashboardLayout/products/index'
import { Route as dashboardDDashboardLayoutCategoriesIndexImport } from './routes/(dashboard)/d/_dashboardLayout/categories/index'
import { Route as dashboardDDashboardLayoutBrandsIndexImport } from './routes/(dashboard)/d/_dashboardLayout/brands/index'
import { Route as dashboardDDashboardLayoutBannersIndexImport } from './routes/(dashboard)/d/_dashboardLayout/banners/index'

// Create Virtual Routes

const mainImport = createFileRoute('/(main)')()
const dashboardDImport = createFileRoute('/(dashboard)/d')()
const mainHomeLayoutprofileImport = createFileRoute(
  '/(main)/_homeLayout/(profile)',
)()
const mainHomeLayoutCartIndexLazyImport = createFileRoute(
  '/(main)/_homeLayout/cart/',
)()
const mainHomeLayoutSellerSellerIdIndexLazyImport = createFileRoute(
  '/(main)/_homeLayout/seller/$sellerId/',
)()
const mainHomeLayoutTitleProductIdIndexLazyImport = createFileRoute(
  '/(main)/_homeLayout/$title/$productId/',
)()
const dashboardDDashboardLayoutOverviewIndexLazyImport = createFileRoute(
  '/(dashboard)/d/_dashboardLayout/overview/',
)()
const dashboardDDashboardLayoutOrdersIndexLazyImport = createFileRoute(
  '/(dashboard)/d/_dashboardLayout/orders/',
)()
const mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyImport =
  createFileRoute(
    '/(main)/_homeLayout/(profile)/_profileLayout/security-settings/',
  )()
const mainHomeLayoutprofileProfileLayoutReturnsIndexLazyImport =
  createFileRoute('/(main)/_homeLayout/(profile)/_profileLayout/returns/')()
const mainHomeLayoutprofileProfileLayoutProfileIndexLazyImport =
  createFileRoute('/(main)/_homeLayout/(profile)/_profileLayout/profile/')()
const mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyImport =
  createFileRoute('/(main)/_homeLayout/(profile)/_profileLayout/payments/')()
const mainHomeLayoutprofileProfileLayoutOrdersIndexLazyImport = createFileRoute(
  '/(main)/_homeLayout/(profile)/_profileLayout/orders/',
)()
const mainHomeLayoutprofileProfileLayoutAddressesIndexLazyImport =
  createFileRoute('/(main)/_homeLayout/(profile)/_profileLayout/addresses/')()
const dashboardDDashboardLayoutProductsNewIndexLazyImport = createFileRoute(
  '/(dashboard)/d/_dashboardLayout/products/new/',
)()
const dashboardDDashboardLayoutProductsProductIdIndexLazyImport =
  createFileRoute('/(dashboard)/d/_dashboardLayout/products/$productId/')()
const mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyImport =
  createFileRoute(
    '/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/',
  )()
const dashboardDDashboardLayoutProductsEditProductIdIndexLazyImport =
  createFileRoute('/(dashboard)/d/_dashboardLayout/products/edit/$productId/')()
const mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyImport =
  createFileRoute(
    '/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/',
  )()

// Create/Update Routes

const mainRoute = mainImport.update({
  id: '/(main)',
  getParentRoute: () => rootRoute,
} as any)

const dashboardDRoute = dashboardDImport.update({
  id: '/(dashboard)/d',
  path: '/d',
  getParentRoute: () => rootRoute,
} as any)

const mainHomeLayoutRoute = mainHomeLayoutImport.update({
  id: '/_homeLayout',
  getParentRoute: () => mainRoute,
} as any)

const mainHomeLayoutprofileRoute = mainHomeLayoutprofileImport.update({
  id: '/(profile)',
  getParentRoute: () => mainHomeLayoutRoute,
} as any)

const mainHomeLayoutIndexRoute = mainHomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainHomeLayoutRoute,
} as any)

const dashboardDDashboardLayoutRoute = dashboardDDashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => dashboardDRoute,
} as any)

const mainHomeLayoutCartIndexLazyRoute = mainHomeLayoutCartIndexLazyImport
  .update({
    id: '/cart/',
    path: '/cart/',
    getParentRoute: () => mainHomeLayoutRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/_homeLayout/cart/index.lazy').then((d) => d.Route),
  )

const mainHomeLayoutWishlistIndexRoute =
  mainHomeLayoutWishlistIndexImport.update({
    id: '/wishlist/',
    path: '/wishlist/',
    getParentRoute: () => mainHomeLayoutRoute,
  } as any)

const dashboardDPartnersIndexRoute = dashboardDPartnersIndexImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => dashboardDRoute,
} as any)

const mainHomeLayoutprofileProfileLayoutRoute =
  mainHomeLayoutprofileProfileLayoutImport.update({
    id: '/_profileLayout',
    getParentRoute: () => mainHomeLayoutprofileRoute,
  } as any)

const mainHomeLayoutSellerSellerIdIndexLazyRoute =
  mainHomeLayoutSellerSellerIdIndexLazyImport
    .update({
      id: '/seller/$sellerId/',
      path: '/seller/$sellerId/',
      getParentRoute: () => mainHomeLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(main)/_homeLayout/seller/$sellerId/index.lazy').then(
        (d) => d.Route,
      ),
    )

const mainHomeLayoutTitleProductIdIndexLazyRoute =
  mainHomeLayoutTitleProductIdIndexLazyImport
    .update({
      id: '/$title/$productId/',
      path: '/$title/$productId/',
      getParentRoute: () => mainHomeLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(main)/_homeLayout/$title/$productId/index.lazy').then(
        (d) => d.Route,
      ),
    )

const dashboardDDashboardLayoutOverviewIndexLazyRoute =
  dashboardDDashboardLayoutOverviewIndexLazyImport
    .update({
      id: '/overview/',
      path: '/overview/',
      getParentRoute: () => dashboardDDashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(dashboard)/d/_dashboardLayout/overview/index.lazy'
      ).then((d) => d.Route),
    )

const dashboardDDashboardLayoutOrdersIndexLazyRoute =
  dashboardDDashboardLayoutOrdersIndexLazyImport
    .update({
      id: '/orders/',
      path: '/orders/',
      getParentRoute: () => dashboardDDashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/d/_dashboardLayout/orders/index.lazy').then(
        (d) => d.Route,
      ),
    )

const dashboardDDashboardLayoutProductsIndexRoute =
  dashboardDDashboardLayoutProductsIndexImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => dashboardDDashboardLayoutRoute,
  } as any)

const dashboardDDashboardLayoutCategoriesIndexRoute =
  dashboardDDashboardLayoutCategoriesIndexImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => dashboardDDashboardLayoutRoute,
  } as any)

const dashboardDDashboardLayoutBrandsIndexRoute =
  dashboardDDashboardLayoutBrandsIndexImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => dashboardDDashboardLayoutRoute,
  } as any)

const dashboardDDashboardLayoutBannersIndexRoute =
  dashboardDDashboardLayoutBannersIndexImport.update({
    id: '/banners/',
    path: '/banners/',
    getParentRoute: () => dashboardDDashboardLayoutRoute,
  } as any)

const mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyImport
    .update({
      id: '/security-settings/',
      path: '/security-settings/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/security-settings/index.lazy'
      ).then((d) => d.Route),
    )

const mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutReturnsIndexLazyImport
    .update({
      id: '/returns/',
      path: '/returns/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/returns/index.lazy'
      ).then((d) => d.Route),
    )

const mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutProfileIndexLazyImport
    .update({
      id: '/profile/',
      path: '/profile/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/profile/index.lazy'
      ).then((d) => d.Route),
    )

const mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyImport
    .update({
      id: '/payments/',
      path: '/payments/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/payments/index.lazy'
      ).then((d) => d.Route),
    )

const mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutOrdersIndexLazyImport
    .update({
      id: '/orders/',
      path: '/orders/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/orders/index.lazy'
      ).then((d) => d.Route),
    )

const mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutAddressesIndexLazyImport
    .update({
      id: '/addresses/',
      path: '/addresses/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/addresses/index.lazy'
      ).then((d) => d.Route),
    )

const dashboardDDashboardLayoutProductsNewIndexLazyRoute =
  dashboardDDashboardLayoutProductsNewIndexLazyImport
    .update({
      id: '/products/new/',
      path: '/products/new/',
      getParentRoute: () => dashboardDDashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(dashboard)/d/_dashboardLayout/products/new/index.lazy'
      ).then((d) => d.Route),
    )

const dashboardDDashboardLayoutProductsProductIdIndexLazyRoute =
  dashboardDDashboardLayoutProductsProductIdIndexLazyImport
    .update({
      id: '/products/$productId/',
      path: '/products/$productId/',
      getParentRoute: () => dashboardDDashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(dashboard)/d/_dashboardLayout/products/$productId/index.lazy'
      ).then((d) => d.Route),
    )

const mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyImport
    .update({
      id: '/orders/$orderId/',
      path: '/orders/$orderId/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/index.lazy'
      ).then((d) => d.Route),
    )

const dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute =
  dashboardDDashboardLayoutProductsEditProductIdIndexLazyImport
    .update({
      id: '/products/edit/$productId/',
      path: '/products/edit/$productId/',
      getParentRoute: () => dashboardDDashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(dashboard)/d/_dashboardLayout/products/edit/$productId/index.lazy'
      ).then((d) => d.Route),
    )

const mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute =
  mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyImport
    .update({
      id: '/orders/track/order/$orderId/',
      path: '/orders/track/order/$orderId/',
      getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/index.lazy'
      ).then((d) => d.Route),
    )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainImport
      parentRoute: typeof rootRoute
    }
    '/(main)/_homeLayout': {
      id: '/(main)/_homeLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainHomeLayoutImport
      parentRoute: typeof mainRoute
    }
    '/(dashboard)/d': {
      id: '/(dashboard)/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof dashboardDImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/d/_dashboardLayout': {
      id: '/(dashboard)/d/_dashboardLayout'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof dashboardDDashboardLayoutImport
      parentRoute: typeof dashboardDRoute
    }
    '/(main)/_homeLayout/': {
      id: '/(main)/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainHomeLayoutIndexImport
      parentRoute: typeof mainHomeLayoutImport
    }
    '/(main)/_homeLayout/(profile)': {
      id: '/(main)/_homeLayout/(profile)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainHomeLayoutprofileImport
      parentRoute: typeof mainHomeLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutImport
      parentRoute: typeof mainHomeLayoutprofileRoute
    }
    '/(dashboard)/d/partners/': {
      id: '/(dashboard)/d/partners/'
      path: '/partners'
      fullPath: '/d/partners'
      preLoaderRoute: typeof dashboardDPartnersIndexImport
      parentRoute: typeof dashboardDImport
    }
    '/(main)/_homeLayout/wishlist/': {
      id: '/(main)/_homeLayout/wishlist/'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof mainHomeLayoutWishlistIndexImport
      parentRoute: typeof mainHomeLayoutImport
    }
    '/(main)/_homeLayout/cart/': {
      id: '/(main)/_homeLayout/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof mainHomeLayoutCartIndexLazyImport
      parentRoute: typeof mainHomeLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/banners/': {
      id: '/(dashboard)/d/_dashboardLayout/banners/'
      path: '/banners'
      fullPath: '/d/banners'
      preLoaderRoute: typeof dashboardDDashboardLayoutBannersIndexImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/brands/': {
      id: '/(dashboard)/d/_dashboardLayout/brands/'
      path: '/brands'
      fullPath: '/d/brands'
      preLoaderRoute: typeof dashboardDDashboardLayoutBrandsIndexImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/categories/': {
      id: '/(dashboard)/d/_dashboardLayout/categories/'
      path: '/categories'
      fullPath: '/d/categories'
      preLoaderRoute: typeof dashboardDDashboardLayoutCategoriesIndexImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/products/': {
      id: '/(dashboard)/d/_dashboardLayout/products/'
      path: '/products'
      fullPath: '/d/products'
      preLoaderRoute: typeof dashboardDDashboardLayoutProductsIndexImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/orders/': {
      id: '/(dashboard)/d/_dashboardLayout/orders/'
      path: '/orders'
      fullPath: '/d/orders'
      preLoaderRoute: typeof dashboardDDashboardLayoutOrdersIndexLazyImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/overview/': {
      id: '/(dashboard)/d/_dashboardLayout/overview/'
      path: '/overview'
      fullPath: '/d/overview'
      preLoaderRoute: typeof dashboardDDashboardLayoutOverviewIndexLazyImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(main)/_homeLayout/$title/$productId/': {
      id: '/(main)/_homeLayout/$title/$productId/'
      path: '/$title/$productId'
      fullPath: '/$title/$productId'
      preLoaderRoute: typeof mainHomeLayoutTitleProductIdIndexLazyImport
      parentRoute: typeof mainHomeLayoutImport
    }
    '/(main)/_homeLayout/seller/$sellerId/': {
      id: '/(main)/_homeLayout/seller/$sellerId/'
      path: '/seller/$sellerId'
      fullPath: '/seller/$sellerId'
      preLoaderRoute: typeof mainHomeLayoutSellerSellerIdIndexLazyImport
      parentRoute: typeof mainHomeLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/products/$productId/': {
      id: '/(dashboard)/d/_dashboardLayout/products/$productId/'
      path: '/products/$productId'
      fullPath: '/d/products/$productId'
      preLoaderRoute: typeof dashboardDDashboardLayoutProductsProductIdIndexLazyImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/products/new/': {
      id: '/(dashboard)/d/_dashboardLayout/products/new/'
      path: '/products/new'
      fullPath: '/d/products/new'
      preLoaderRoute: typeof dashboardDDashboardLayoutProductsNewIndexLazyImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/addresses/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/addresses/'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/orders/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/payments/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/profile/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/returns/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/returns/'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/security-settings/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/security-settings/'
      path: '/security-settings'
      fullPath: '/security-settings'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
    '/(dashboard)/d/_dashboardLayout/products/edit/$productId/': {
      id: '/(dashboard)/d/_dashboardLayout/products/edit/$productId/'
      path: '/products/edit/$productId'
      fullPath: '/d/products/edit/$productId'
      preLoaderRoute: typeof dashboardDDashboardLayoutProductsEditProductIdIndexLazyImport
      parentRoute: typeof dashboardDDashboardLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
    '/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/': {
      id: '/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/'
      path: '/orders/track/order/$orderId'
      fullPath: '/orders/track/order/$orderId'
      preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyImport
      parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport
    }
  }
}

// Create and export the route tree

interface mainHomeLayoutprofileProfileLayoutRouteChildren {
  mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute
  mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute
  mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute
  mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute
  mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute
  mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute
  mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute
  mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute
}

const mainHomeLayoutprofileProfileLayoutRouteChildren: mainHomeLayoutprofileProfileLayoutRouteChildren =
  {
    mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute,
    mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute,
    mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute,
    mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute,
    mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute,
    mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute,
    mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute,
    mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute:
      mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute,
  }

const mainHomeLayoutprofileProfileLayoutRouteWithChildren =
  mainHomeLayoutprofileProfileLayoutRoute._addFileChildren(
    mainHomeLayoutprofileProfileLayoutRouteChildren,
  )

interface mainHomeLayoutprofileRouteChildren {
  mainHomeLayoutprofileProfileLayoutRoute: typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren
}

const mainHomeLayoutprofileRouteChildren: mainHomeLayoutprofileRouteChildren = {
  mainHomeLayoutprofileProfileLayoutRoute:
    mainHomeLayoutprofileProfileLayoutRouteWithChildren,
}

const mainHomeLayoutprofileRouteWithChildren =
  mainHomeLayoutprofileRoute._addFileChildren(
    mainHomeLayoutprofileRouteChildren,
  )

interface mainHomeLayoutRouteChildren {
  mainHomeLayoutIndexRoute: typeof mainHomeLayoutIndexRoute
  mainHomeLayoutprofileRoute: typeof mainHomeLayoutprofileRouteWithChildren
  mainHomeLayoutWishlistIndexRoute: typeof mainHomeLayoutWishlistIndexRoute
  mainHomeLayoutCartIndexLazyRoute: typeof mainHomeLayoutCartIndexLazyRoute
  mainHomeLayoutTitleProductIdIndexLazyRoute: typeof mainHomeLayoutTitleProductIdIndexLazyRoute
  mainHomeLayoutSellerSellerIdIndexLazyRoute: typeof mainHomeLayoutSellerSellerIdIndexLazyRoute
}

const mainHomeLayoutRouteChildren: mainHomeLayoutRouteChildren = {
  mainHomeLayoutIndexRoute: mainHomeLayoutIndexRoute,
  mainHomeLayoutprofileRoute: mainHomeLayoutprofileRouteWithChildren,
  mainHomeLayoutWishlistIndexRoute: mainHomeLayoutWishlistIndexRoute,
  mainHomeLayoutCartIndexLazyRoute: mainHomeLayoutCartIndexLazyRoute,
  mainHomeLayoutTitleProductIdIndexLazyRoute:
    mainHomeLayoutTitleProductIdIndexLazyRoute,
  mainHomeLayoutSellerSellerIdIndexLazyRoute:
    mainHomeLayoutSellerSellerIdIndexLazyRoute,
}

const mainHomeLayoutRouteWithChildren = mainHomeLayoutRoute._addFileChildren(
  mainHomeLayoutRouteChildren,
)

interface mainRouteChildren {
  mainHomeLayoutRoute: typeof mainHomeLayoutRouteWithChildren
}

const mainRouteChildren: mainRouteChildren = {
  mainHomeLayoutRoute: mainHomeLayoutRouteWithChildren,
}

const mainRouteWithChildren = mainRoute._addFileChildren(mainRouteChildren)

interface dashboardDDashboardLayoutRouteChildren {
  dashboardDDashboardLayoutBannersIndexRoute: typeof dashboardDDashboardLayoutBannersIndexRoute
  dashboardDDashboardLayoutBrandsIndexRoute: typeof dashboardDDashboardLayoutBrandsIndexRoute
  dashboardDDashboardLayoutCategoriesIndexRoute: typeof dashboardDDashboardLayoutCategoriesIndexRoute
  dashboardDDashboardLayoutProductsIndexRoute: typeof dashboardDDashboardLayoutProductsIndexRoute
  dashboardDDashboardLayoutOrdersIndexLazyRoute: typeof dashboardDDashboardLayoutOrdersIndexLazyRoute
  dashboardDDashboardLayoutOverviewIndexLazyRoute: typeof dashboardDDashboardLayoutOverviewIndexLazyRoute
  dashboardDDashboardLayoutProductsProductIdIndexLazyRoute: typeof dashboardDDashboardLayoutProductsProductIdIndexLazyRoute
  dashboardDDashboardLayoutProductsNewIndexLazyRoute: typeof dashboardDDashboardLayoutProductsNewIndexLazyRoute
  dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute: typeof dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute
}

const dashboardDDashboardLayoutRouteChildren: dashboardDDashboardLayoutRouteChildren =
  {
    dashboardDDashboardLayoutBannersIndexRoute:
      dashboardDDashboardLayoutBannersIndexRoute,
    dashboardDDashboardLayoutBrandsIndexRoute:
      dashboardDDashboardLayoutBrandsIndexRoute,
    dashboardDDashboardLayoutCategoriesIndexRoute:
      dashboardDDashboardLayoutCategoriesIndexRoute,
    dashboardDDashboardLayoutProductsIndexRoute:
      dashboardDDashboardLayoutProductsIndexRoute,
    dashboardDDashboardLayoutOrdersIndexLazyRoute:
      dashboardDDashboardLayoutOrdersIndexLazyRoute,
    dashboardDDashboardLayoutOverviewIndexLazyRoute:
      dashboardDDashboardLayoutOverviewIndexLazyRoute,
    dashboardDDashboardLayoutProductsProductIdIndexLazyRoute:
      dashboardDDashboardLayoutProductsProductIdIndexLazyRoute,
    dashboardDDashboardLayoutProductsNewIndexLazyRoute:
      dashboardDDashboardLayoutProductsNewIndexLazyRoute,
    dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute:
      dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute,
  }

const dashboardDDashboardLayoutRouteWithChildren =
  dashboardDDashboardLayoutRoute._addFileChildren(
    dashboardDDashboardLayoutRouteChildren,
  )

interface dashboardDRouteChildren {
  dashboardDDashboardLayoutRoute: typeof dashboardDDashboardLayoutRouteWithChildren
  dashboardDPartnersIndexRoute: typeof dashboardDPartnersIndexRoute
}

const dashboardDRouteChildren: dashboardDRouteChildren = {
  dashboardDDashboardLayoutRoute: dashboardDDashboardLayoutRouteWithChildren,
  dashboardDPartnersIndexRoute: dashboardDPartnersIndexRoute,
}

const dashboardDRouteWithChildren = dashboardDRoute._addFileChildren(
  dashboardDRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren
  '/d': typeof dashboardDDashboardLayoutRouteWithChildren
  '/d/partners': typeof dashboardDPartnersIndexRoute
  '/wishlist': typeof mainHomeLayoutWishlistIndexRoute
  '/cart': typeof mainHomeLayoutCartIndexLazyRoute
  '/d/banners': typeof dashboardDDashboardLayoutBannersIndexRoute
  '/d/brands': typeof dashboardDDashboardLayoutBrandsIndexRoute
  '/d/categories': typeof dashboardDDashboardLayoutCategoriesIndexRoute
  '/d/products': typeof dashboardDDashboardLayoutProductsIndexRoute
  '/d/orders': typeof dashboardDDashboardLayoutOrdersIndexLazyRoute
  '/d/overview': typeof dashboardDDashboardLayoutOverviewIndexLazyRoute
  '/$title/$productId': typeof mainHomeLayoutTitleProductIdIndexLazyRoute
  '/seller/$sellerId': typeof mainHomeLayoutSellerSellerIdIndexLazyRoute
  '/d/products/$productId': typeof dashboardDDashboardLayoutProductsProductIdIndexLazyRoute
  '/d/products/new': typeof dashboardDDashboardLayoutProductsNewIndexLazyRoute
  '/addresses': typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute
  '/orders': typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute
  '/payments': typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute
  '/profile': typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute
  '/returns': typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute
  '/security-settings': typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute
  '/d/products/edit/$productId': typeof dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute
  '/orders/$orderId': typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute
  '/orders/track/order/$orderId': typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/d': typeof dashboardDDashboardLayoutRouteWithChildren
  '/': typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren
  '/d/partners': typeof dashboardDPartnersIndexRoute
  '/wishlist': typeof mainHomeLayoutWishlistIndexRoute
  '/cart': typeof mainHomeLayoutCartIndexLazyRoute
  '/d/banners': typeof dashboardDDashboardLayoutBannersIndexRoute
  '/d/brands': typeof dashboardDDashboardLayoutBrandsIndexRoute
  '/d/categories': typeof dashboardDDashboardLayoutCategoriesIndexRoute
  '/d/products': typeof dashboardDDashboardLayoutProductsIndexRoute
  '/d/orders': typeof dashboardDDashboardLayoutOrdersIndexLazyRoute
  '/d/overview': typeof dashboardDDashboardLayoutOverviewIndexLazyRoute
  '/$title/$productId': typeof mainHomeLayoutTitleProductIdIndexLazyRoute
  '/seller/$sellerId': typeof mainHomeLayoutSellerSellerIdIndexLazyRoute
  '/d/products/$productId': typeof dashboardDDashboardLayoutProductsProductIdIndexLazyRoute
  '/d/products/new': typeof dashboardDDashboardLayoutProductsNewIndexLazyRoute
  '/addresses': typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute
  '/orders': typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute
  '/payments': typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute
  '/profile': typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute
  '/returns': typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute
  '/security-settings': typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute
  '/d/products/edit/$productId': typeof dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute
  '/orders/$orderId': typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute
  '/orders/track/order/$orderId': typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(main)': typeof mainRouteWithChildren
  '/(main)/_homeLayout': typeof mainHomeLayoutRouteWithChildren
  '/(dashboard)/d': typeof dashboardDRouteWithChildren
  '/(dashboard)/d/_dashboardLayout': typeof dashboardDDashboardLayoutRouteWithChildren
  '/(main)/_homeLayout/': typeof mainHomeLayoutIndexRoute
  '/(main)/_homeLayout/(profile)': typeof mainHomeLayoutprofileRouteWithChildren
  '/(main)/_homeLayout/(profile)/_profileLayout': typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren
  '/(dashboard)/d/partners/': typeof dashboardDPartnersIndexRoute
  '/(main)/_homeLayout/wishlist/': typeof mainHomeLayoutWishlistIndexRoute
  '/(main)/_homeLayout/cart/': typeof mainHomeLayoutCartIndexLazyRoute
  '/(dashboard)/d/_dashboardLayout/banners/': typeof dashboardDDashboardLayoutBannersIndexRoute
  '/(dashboard)/d/_dashboardLayout/brands/': typeof dashboardDDashboardLayoutBrandsIndexRoute
  '/(dashboard)/d/_dashboardLayout/categories/': typeof dashboardDDashboardLayoutCategoriesIndexRoute
  '/(dashboard)/d/_dashboardLayout/products/': typeof dashboardDDashboardLayoutProductsIndexRoute
  '/(dashboard)/d/_dashboardLayout/orders/': typeof dashboardDDashboardLayoutOrdersIndexLazyRoute
  '/(dashboard)/d/_dashboardLayout/overview/': typeof dashboardDDashboardLayoutOverviewIndexLazyRoute
  '/(main)/_homeLayout/$title/$productId/': typeof mainHomeLayoutTitleProductIdIndexLazyRoute
  '/(main)/_homeLayout/seller/$sellerId/': typeof mainHomeLayoutSellerSellerIdIndexLazyRoute
  '/(dashboard)/d/_dashboardLayout/products/$productId/': typeof dashboardDDashboardLayoutProductsProductIdIndexLazyRoute
  '/(dashboard)/d/_dashboardLayout/products/new/': typeof dashboardDDashboardLayoutProductsNewIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/addresses/': typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/orders/': typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/payments/': typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/profile/': typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/returns/': typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/security-settings/': typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute
  '/(dashboard)/d/_dashboardLayout/products/edit/$productId/': typeof dashboardDDashboardLayoutProductsEditProductIdIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/': typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute
  '/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/': typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/d'
    | '/d/partners'
    | '/wishlist'
    | '/cart'
    | '/d/banners'
    | '/d/brands'
    | '/d/categories'
    | '/d/products'
    | '/d/orders'
    | '/d/overview'
    | '/$title/$productId'
    | '/seller/$sellerId'
    | '/d/products/$productId'
    | '/d/products/new'
    | '/addresses'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/returns'
    | '/security-settings'
    | '/d/products/edit/$productId'
    | '/orders/$orderId'
    | '/orders/track/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/d'
    | '/'
    | '/d/partners'
    | '/wishlist'
    | '/cart'
    | '/d/banners'
    | '/d/brands'
    | '/d/categories'
    | '/d/products'
    | '/d/orders'
    | '/d/overview'
    | '/$title/$productId'
    | '/seller/$sellerId'
    | '/d/products/$productId'
    | '/d/products/new'
    | '/addresses'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/returns'
    | '/security-settings'
    | '/d/products/edit/$productId'
    | '/orders/$orderId'
    | '/orders/track/order/$orderId'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/_homeLayout'
    | '/(dashboard)/d'
    | '/(dashboard)/d/_dashboardLayout'
    | '/(main)/_homeLayout/'
    | '/(main)/_homeLayout/(profile)'
    | '/(main)/_homeLayout/(profile)/_profileLayout'
    | '/(dashboard)/d/partners/'
    | '/(main)/_homeLayout/wishlist/'
    | '/(main)/_homeLayout/cart/'
    | '/(dashboard)/d/_dashboardLayout/banners/'
    | '/(dashboard)/d/_dashboardLayout/brands/'
    | '/(dashboard)/d/_dashboardLayout/categories/'
    | '/(dashboard)/d/_dashboardLayout/products/'
    | '/(dashboard)/d/_dashboardLayout/orders/'
    | '/(dashboard)/d/_dashboardLayout/overview/'
    | '/(main)/_homeLayout/$title/$productId/'
    | '/(main)/_homeLayout/seller/$sellerId/'
    | '/(dashboard)/d/_dashboardLayout/products/$productId/'
    | '/(dashboard)/d/_dashboardLayout/products/new/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/addresses/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/orders/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/payments/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/profile/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/returns/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/security-settings/'
    | '/(dashboard)/d/_dashboardLayout/products/edit/$productId/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/'
    | '/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  mainRoute: typeof mainRouteWithChildren
  dashboardDRoute: typeof dashboardDRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  mainRoute: mainRouteWithChildren,
  dashboardDRoute: dashboardDRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(main)",
        "/(dashboard)/d"
      ]
    },
    "/(main)": {
      "filePath": "(main)",
      "children": [
        "/(main)/_homeLayout"
      ]
    },
    "/(main)/_homeLayout": {
      "filePath": "(main)/_homeLayout.tsx",
      "parent": "/(main)",
      "children": [
        "/(main)/_homeLayout/",
        "/(main)/_homeLayout/(profile)",
        "/(main)/_homeLayout/wishlist/",
        "/(main)/_homeLayout/cart/",
        "/(main)/_homeLayout/$title/$productId/",
        "/(main)/_homeLayout/seller/$sellerId/"
      ]
    },
    "/(dashboard)/d": {
      "filePath": "(dashboard)/d",
      "children": [
        "/(dashboard)/d/_dashboardLayout",
        "/(dashboard)/d/partners/"
      ]
    },
    "/(dashboard)/d/_dashboardLayout": {
      "filePath": "(dashboard)/d/_dashboardLayout.tsx",
      "parent": "/(dashboard)/d",
      "children": [
        "/(dashboard)/d/_dashboardLayout/banners/",
        "/(dashboard)/d/_dashboardLayout/brands/",
        "/(dashboard)/d/_dashboardLayout/categories/",
        "/(dashboard)/d/_dashboardLayout/products/",
        "/(dashboard)/d/_dashboardLayout/orders/",
        "/(dashboard)/d/_dashboardLayout/overview/",
        "/(dashboard)/d/_dashboardLayout/products/$productId/",
        "/(dashboard)/d/_dashboardLayout/products/new/",
        "/(dashboard)/d/_dashboardLayout/products/edit/$productId/"
      ]
    },
    "/(main)/_homeLayout/": {
      "filePath": "(main)/_homeLayout/index.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(main)/_homeLayout/(profile)": {
      "filePath": "(main)/_homeLayout/(profile)",
      "parent": "/(main)/_homeLayout",
      "children": [
        "/(main)/_homeLayout/(profile)/_profileLayout"
      ]
    },
    "/(main)/_homeLayout/(profile)/_profileLayout": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout.tsx",
      "parent": "/(main)/_homeLayout/(profile)",
      "children": [
        "/(main)/_homeLayout/(profile)/_profileLayout/addresses/",
        "/(main)/_homeLayout/(profile)/_profileLayout/orders/",
        "/(main)/_homeLayout/(profile)/_profileLayout/payments/",
        "/(main)/_homeLayout/(profile)/_profileLayout/profile/",
        "/(main)/_homeLayout/(profile)/_profileLayout/returns/",
        "/(main)/_homeLayout/(profile)/_profileLayout/security-settings/",
        "/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/",
        "/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/"
      ]
    },
    "/(dashboard)/d/partners/": {
      "filePath": "(dashboard)/d/partners/index.tsx",
      "parent": "/(dashboard)/d"
    },
    "/(main)/_homeLayout/wishlist/": {
      "filePath": "(main)/_homeLayout/wishlist/index.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(main)/_homeLayout/cart/": {
      "filePath": "(main)/_homeLayout/cart/index.lazy.ts",
      "parent": "/(main)/_homeLayout"
    },
    "/(dashboard)/d/_dashboardLayout/banners/": {
      "filePath": "(dashboard)/d/_dashboardLayout/banners/index.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(dashboard)/d/_dashboardLayout/brands/": {
      "filePath": "(dashboard)/d/_dashboardLayout/brands/index.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(dashboard)/d/_dashboardLayout/categories/": {
      "filePath": "(dashboard)/d/_dashboardLayout/categories/index.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(dashboard)/d/_dashboardLayout/products/": {
      "filePath": "(dashboard)/d/_dashboardLayout/products/index.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(dashboard)/d/_dashboardLayout/orders/": {
      "filePath": "(dashboard)/d/_dashboardLayout/orders/index.lazy.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(dashboard)/d/_dashboardLayout/overview/": {
      "filePath": "(dashboard)/d/_dashboardLayout/overview/index.lazy.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(main)/_homeLayout/$title/$productId/": {
      "filePath": "(main)/_homeLayout/$title/$productId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(main)/_homeLayout/seller/$sellerId/": {
      "filePath": "(main)/_homeLayout/seller/$sellerId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(dashboard)/d/_dashboardLayout/products/$productId/": {
      "filePath": "(dashboard)/d/_dashboardLayout/products/$productId/index.lazy.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(dashboard)/d/_dashboardLayout/products/new/": {
      "filePath": "(dashboard)/d/_dashboardLayout/products/new/index.lazy.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/addresses/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/addresses/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/orders/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/orders/index.lazy.ts",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/payments/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/payments/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/profile/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/profile/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/returns/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/returns/index.lazy.ts",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/security-settings/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/security-settings/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(dashboard)/d/_dashboardLayout/products/edit/$productId/": {
      "filePath": "(dashboard)/d/_dashboardLayout/products/edit/$productId/index.lazy.tsx",
      "parent": "/(dashboard)/d/_dashboardLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    }
  }
}
ROUTE_MANIFEST_END */
