/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as mainHomeLayoutImport } from "./routes/(main)/_homeLayout";
import { Route as dashboardDashboardLayoutImport } from "./routes/(dashboard)/_dashboardLayout";
import { Route as mainHomeLayoutIndexImport } from "./routes/(main)/_homeLayout/index";
import { Route as dashboardPartnersIndexImport } from "./routes/(dashboard)/partners/index";
import { Route as mainHomeLayoutWishlistIndexImport } from "./routes/(main)/_homeLayout/wishlist/index";
import { Route as dashboardDashboardLayoutDashboardIndexImport } from "./routes/(dashboard)/_dashboardLayout/dashboard/index";
import { Route as mainHomeLayoutprofileProfileLayoutImport } from "./routes/(main)/_homeLayout/(profile)/_profileLayout";
import { Route as dashboardDashboardLayoutDashboardProductsIndexImport } from "./routes/(dashboard)/_dashboardLayout/dashboard/products/index";
import { Route as dashboardDashboardLayoutDashboardOrdersIndexImport } from "./routes/(dashboard)/_dashboardLayout/dashboard/orders/index";
import { Route as dashboardDashboardLayoutDashboardProductsNewIndexImport } from "./routes/(dashboard)/_dashboardLayout/dashboard/products/new/index";
import { Route as dashboardDashboardLayoutDashboardProductsEditProductIdIndexImport } from "./routes/(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/index";

// Create Virtual Routes

const mainImport = createFileRoute("/(main)")();
const dashboardImport = createFileRoute("/(dashboard)")();
const mainHomeLayoutprofileImport = createFileRoute("/(main)/_homeLayout/(profile)")();
const mainHomeLayoutCartIndexLazyImport = createFileRoute("/(main)/_homeLayout/cart/")();
const mainHomeLayoutSellerSellerIdIndexLazyImport = createFileRoute("/(main)/_homeLayout/seller/$sellerId/")();
const mainHomeLayoutTitleProductIdIndexLazyImport = createFileRoute("/(main)/_homeLayout/$title/$productId/")();
const mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/security-settings/",
)();
const mainHomeLayoutprofileProfileLayoutReturnsIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/returns/",
)();
const mainHomeLayoutprofileProfileLayoutProfileIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/profile/",
)();
const mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/payments/",
)();
const mainHomeLayoutprofileProfileLayoutOrdersIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/orders/",
)();
const mainHomeLayoutprofileProfileLayoutAddressesIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/addresses/",
)();
const mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/",
)();
const mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyImport = createFileRoute(
	"/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/",
)();

// Create/Update Routes

const mainRoute = mainImport.update({
	id: "/(main)",
	getParentRoute: () => rootRoute,
} as any);

const dashboardRoute = dashboardImport.update({
	id: "/(dashboard)",
	getParentRoute: () => rootRoute,
} as any);

const mainHomeLayoutRoute = mainHomeLayoutImport.update({
	id: "/_homeLayout",
	getParentRoute: () => mainRoute,
} as any);

const dashboardDashboardLayoutRoute = dashboardDashboardLayoutImport.update({
	id: "/_dashboardLayout",
	getParentRoute: () => dashboardRoute,
} as any);

const mainHomeLayoutprofileRoute = mainHomeLayoutprofileImport.update({
	id: "/(profile)",
	getParentRoute: () => mainHomeLayoutRoute,
} as any);

const mainHomeLayoutIndexRoute = mainHomeLayoutIndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => mainHomeLayoutRoute,
} as any);

const dashboardPartnersIndexRoute = dashboardPartnersIndexImport.update({
	id: "/partners/",
	path: "/partners/",
	getParentRoute: () => dashboardRoute,
} as any);

const mainHomeLayoutCartIndexLazyRoute = mainHomeLayoutCartIndexLazyImport
	.update({
		id: "/cart/",
		path: "/cart/",
		getParentRoute: () => mainHomeLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/cart/index.lazy").then((d) => d.Route));

const mainHomeLayoutWishlistIndexRoute = mainHomeLayoutWishlistIndexImport.update({
	id: "/wishlist/",
	path: "/wishlist/",
	getParentRoute: () => mainHomeLayoutRoute,
} as any);

const dashboardDashboardLayoutDashboardIndexRoute = dashboardDashboardLayoutDashboardIndexImport.update({
	id: "/dashboard/",
	path: "/dashboard/",
	getParentRoute: () => dashboardDashboardLayoutRoute,
} as any);

const mainHomeLayoutprofileProfileLayoutRoute = mainHomeLayoutprofileProfileLayoutImport.update({
	id: "/_profileLayout",
	getParentRoute: () => mainHomeLayoutprofileRoute,
} as any);

const mainHomeLayoutSellerSellerIdIndexLazyRoute = mainHomeLayoutSellerSellerIdIndexLazyImport
	.update({
		id: "/seller/$sellerId/",
		path: "/seller/$sellerId/",
		getParentRoute: () => mainHomeLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/seller/$sellerId/index.lazy").then((d) => d.Route));

const mainHomeLayoutTitleProductIdIndexLazyRoute = mainHomeLayoutTitleProductIdIndexLazyImport
	.update({
		id: "/$title/$productId/",
		path: "/$title/$productId/",
		getParentRoute: () => mainHomeLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/$title/$productId/index.lazy").then((d) => d.Route));

const dashboardDashboardLayoutDashboardProductsIndexRoute = dashboardDashboardLayoutDashboardProductsIndexImport.update({
	id: "/dashboard/products/",
	path: "/dashboard/products/",
	getParentRoute: () => dashboardDashboardLayoutRoute,
} as any);

const dashboardDashboardLayoutDashboardOrdersIndexRoute = dashboardDashboardLayoutDashboardOrdersIndexImport.update({
	id: "/dashboard/orders/",
	path: "/dashboard/orders/",
	getParentRoute: () => dashboardDashboardLayoutRoute,
} as any);

const mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute =
	mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyImport
		.update({
			id: "/security-settings/",
			path: "/security-settings/",
			getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
		} as any)
		.lazy(() =>
			import("./routes/(main)/_homeLayout/(profile)/_profileLayout/security-settings/index.lazy").then((d) => d.Route),
		);

const mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute = mainHomeLayoutprofileProfileLayoutReturnsIndexLazyImport
	.update({
		id: "/returns/",
		path: "/returns/",
		getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/(profile)/_profileLayout/returns/index.lazy").then((d) => d.Route));

const mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute = mainHomeLayoutprofileProfileLayoutProfileIndexLazyImport
	.update({
		id: "/profile/",
		path: "/profile/",
		getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/(profile)/_profileLayout/profile/index.lazy").then((d) => d.Route));

const mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute = mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyImport
	.update({
		id: "/payments/",
		path: "/payments/",
		getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/(profile)/_profileLayout/payments/index.lazy").then((d) => d.Route));

const mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute = mainHomeLayoutprofileProfileLayoutOrdersIndexLazyImport
	.update({
		id: "/orders/",
		path: "/orders/",
		getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/(profile)/_profileLayout/orders/index.lazy").then((d) => d.Route));

const mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute = mainHomeLayoutprofileProfileLayoutAddressesIndexLazyImport
	.update({
		id: "/addresses/",
		path: "/addresses/",
		getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
	} as any)
	.lazy(() => import("./routes/(main)/_homeLayout/(profile)/_profileLayout/addresses/index.lazy").then((d) => d.Route));

const dashboardDashboardLayoutDashboardProductsNewIndexRoute = dashboardDashboardLayoutDashboardProductsNewIndexImport.update({
	id: "/dashboard/products/new/",
	path: "/dashboard/products/new/",
	getParentRoute: () => dashboardDashboardLayoutRoute,
} as any);

const mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute =
	mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyImport
		.update({
			id: "/orders/$orderId/",
			path: "/orders/$orderId/",
			getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
		} as any)
		.lazy(() =>
			import("./routes/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/index.lazy").then((d) => d.Route),
		);

const dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute =
	dashboardDashboardLayoutDashboardProductsEditProductIdIndexImport.update({
		id: "/dashboard/products/edit/$productId/",
		path: "/dashboard/products/edit/$productId/",
		getParentRoute: () => dashboardDashboardLayoutRoute,
	} as any);

const mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute =
	mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyImport
		.update({
			id: "/orders/track/order/$orderId/",
			path: "/orders/track/order/$orderId/",
			getParentRoute: () => mainHomeLayoutprofileProfileLayoutRoute,
		} as any)
		.lazy(() =>
			import("./routes/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/index.lazy").then(
				(d) => d.Route,
			),
		);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/(dashboard)": {
			id: "/(dashboard)";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof dashboardImport;
			parentRoute: typeof rootRoute;
		};
		"/(dashboard)/_dashboardLayout": {
			id: "/(dashboard)/_dashboardLayout";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof dashboardDashboardLayoutImport;
			parentRoute: typeof dashboardRoute;
		};
		"/(main)": {
			id: "/(main)";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof mainImport;
			parentRoute: typeof rootRoute;
		};
		"/(main)/_homeLayout": {
			id: "/(main)/_homeLayout";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof mainHomeLayoutImport;
			parentRoute: typeof mainRoute;
		};
		"/(dashboard)/partners/": {
			id: "/(dashboard)/partners/";
			path: "/partners";
			fullPath: "/partners";
			preLoaderRoute: typeof dashboardPartnersIndexImport;
			parentRoute: typeof dashboardImport;
		};
		"/(main)/_homeLayout/": {
			id: "/(main)/_homeLayout/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof mainHomeLayoutIndexImport;
			parentRoute: typeof mainHomeLayoutImport;
		};
		"/(main)/_homeLayout/(profile)": {
			id: "/(main)/_homeLayout/(profile)";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof mainHomeLayoutprofileImport;
			parentRoute: typeof mainHomeLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
			parentRoute: typeof mainHomeLayoutprofileRoute;
		};
		"/(dashboard)/_dashboardLayout/dashboard/": {
			id: "/(dashboard)/_dashboardLayout/dashboard/";
			path: "/dashboard";
			fullPath: "/dashboard";
			preLoaderRoute: typeof dashboardDashboardLayoutDashboardIndexImport;
			parentRoute: typeof dashboardDashboardLayoutImport;
		};
		"/(main)/_homeLayout/wishlist/": {
			id: "/(main)/_homeLayout/wishlist/";
			path: "/wishlist";
			fullPath: "/wishlist";
			preLoaderRoute: typeof mainHomeLayoutWishlistIndexImport;
			parentRoute: typeof mainHomeLayoutImport;
		};
		"/(main)/_homeLayout/cart/": {
			id: "/(main)/_homeLayout/cart/";
			path: "/cart";
			fullPath: "/cart";
			preLoaderRoute: typeof mainHomeLayoutCartIndexLazyImport;
			parentRoute: typeof mainHomeLayoutImport;
		};
		"/(dashboard)/_dashboardLayout/dashboard/orders/": {
			id: "/(dashboard)/_dashboardLayout/dashboard/orders/";
			path: "/dashboard/orders";
			fullPath: "/dashboard/orders";
			preLoaderRoute: typeof dashboardDashboardLayoutDashboardOrdersIndexImport;
			parentRoute: typeof dashboardDashboardLayoutImport;
		};
		"/(dashboard)/_dashboardLayout/dashboard/products/": {
			id: "/(dashboard)/_dashboardLayout/dashboard/products/";
			path: "/dashboard/products";
			fullPath: "/dashboard/products";
			preLoaderRoute: typeof dashboardDashboardLayoutDashboardProductsIndexImport;
			parentRoute: typeof dashboardDashboardLayoutImport;
		};
		"/(main)/_homeLayout/$title/$productId/": {
			id: "/(main)/_homeLayout/$title/$productId/";
			path: "/$title/$productId";
			fullPath: "/$title/$productId";
			preLoaderRoute: typeof mainHomeLayoutTitleProductIdIndexLazyImport;
			parentRoute: typeof mainHomeLayoutImport;
		};
		"/(main)/_homeLayout/seller/$sellerId/": {
			id: "/(main)/_homeLayout/seller/$sellerId/";
			path: "/seller/$sellerId";
			fullPath: "/seller/$sellerId";
			preLoaderRoute: typeof mainHomeLayoutSellerSellerIdIndexLazyImport;
			parentRoute: typeof mainHomeLayoutImport;
		};
		"/(dashboard)/_dashboardLayout/dashboard/products/new/": {
			id: "/(dashboard)/_dashboardLayout/dashboard/products/new/";
			path: "/dashboard/products/new";
			fullPath: "/dashboard/products/new";
			preLoaderRoute: typeof dashboardDashboardLayoutDashboardProductsNewIndexImport;
			parentRoute: typeof dashboardDashboardLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/addresses/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/addresses/";
			path: "/addresses";
			fullPath: "/addresses";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/orders/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/orders/";
			path: "/orders";
			fullPath: "/orders";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/payments/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/payments/";
			path: "/payments";
			fullPath: "/payments";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/profile/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/profile/";
			path: "/profile";
			fullPath: "/profile";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/returns/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/returns/";
			path: "/returns";
			fullPath: "/returns";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/security-settings/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/security-settings/";
			path: "/security-settings";
			fullPath: "/security-settings";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
		"/(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/": {
			id: "/(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/";
			path: "/dashboard/products/edit/$productId";
			fullPath: "/dashboard/products/edit/$productId";
			preLoaderRoute: typeof dashboardDashboardLayoutDashboardProductsEditProductIdIndexImport;
			parentRoute: typeof dashboardDashboardLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/";
			path: "/orders/$orderId";
			fullPath: "/orders/$orderId";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
		"/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/": {
			id: "/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/";
			path: "/orders/track/order/$orderId";
			fullPath: "/orders/track/order/$orderId";
			preLoaderRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyImport;
			parentRoute: typeof mainHomeLayoutprofileProfileLayoutImport;
		};
	}
}

// Create and export the route tree

interface dashboardDashboardLayoutRouteChildren {
	dashboardDashboardLayoutDashboardIndexRoute: typeof dashboardDashboardLayoutDashboardIndexRoute;
	dashboardDashboardLayoutDashboardOrdersIndexRoute: typeof dashboardDashboardLayoutDashboardOrdersIndexRoute;
	dashboardDashboardLayoutDashboardProductsIndexRoute: typeof dashboardDashboardLayoutDashboardProductsIndexRoute;
	dashboardDashboardLayoutDashboardProductsNewIndexRoute: typeof dashboardDashboardLayoutDashboardProductsNewIndexRoute;
	dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute: typeof dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute;
}

const dashboardDashboardLayoutRouteChildren: dashboardDashboardLayoutRouteChildren = {
	dashboardDashboardLayoutDashboardIndexRoute: dashboardDashboardLayoutDashboardIndexRoute,
	dashboardDashboardLayoutDashboardOrdersIndexRoute: dashboardDashboardLayoutDashboardOrdersIndexRoute,
	dashboardDashboardLayoutDashboardProductsIndexRoute: dashboardDashboardLayoutDashboardProductsIndexRoute,
	dashboardDashboardLayoutDashboardProductsNewIndexRoute: dashboardDashboardLayoutDashboardProductsNewIndexRoute,
	dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute:
		dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute,
};

const dashboardDashboardLayoutRouteWithChildren = dashboardDashboardLayoutRoute._addFileChildren(
	dashboardDashboardLayoutRouteChildren,
);

interface dashboardRouteChildren {
	dashboardDashboardLayoutRoute: typeof dashboardDashboardLayoutRouteWithChildren;
	dashboardPartnersIndexRoute: typeof dashboardPartnersIndexRoute;
}

const dashboardRouteChildren: dashboardRouteChildren = {
	dashboardDashboardLayoutRoute: dashboardDashboardLayoutRouteWithChildren,
	dashboardPartnersIndexRoute: dashboardPartnersIndexRoute,
};

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(dashboardRouteChildren);

interface mainHomeLayoutprofileProfileLayoutRouteChildren {
	mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute;
	mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute;
	mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute;
	mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute;
	mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute;
	mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute;
	mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute;
	mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute: typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute;
}

const mainHomeLayoutprofileProfileLayoutRouteChildren: mainHomeLayoutprofileProfileLayoutRouteChildren = {
	mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute: mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute,
	mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute: mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute,
	mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute: mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute,
	mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute: mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute,
	mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute: mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute,
	mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute:
		mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute,
	mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute: mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute,
	mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute:
		mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute,
};

const mainHomeLayoutprofileProfileLayoutRouteWithChildren = mainHomeLayoutprofileProfileLayoutRoute._addFileChildren(
	mainHomeLayoutprofileProfileLayoutRouteChildren,
);

interface mainHomeLayoutprofileRouteChildren {
	mainHomeLayoutprofileProfileLayoutRoute: typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren;
}

const mainHomeLayoutprofileRouteChildren: mainHomeLayoutprofileRouteChildren = {
	mainHomeLayoutprofileProfileLayoutRoute: mainHomeLayoutprofileProfileLayoutRouteWithChildren,
};

const mainHomeLayoutprofileRouteWithChildren = mainHomeLayoutprofileRoute._addFileChildren(mainHomeLayoutprofileRouteChildren);

interface mainHomeLayoutRouteChildren {
	mainHomeLayoutIndexRoute: typeof mainHomeLayoutIndexRoute;
	mainHomeLayoutprofileRoute: typeof mainHomeLayoutprofileRouteWithChildren;
	mainHomeLayoutWishlistIndexRoute: typeof mainHomeLayoutWishlistIndexRoute;
	mainHomeLayoutCartIndexLazyRoute: typeof mainHomeLayoutCartIndexLazyRoute;
	mainHomeLayoutTitleProductIdIndexLazyRoute: typeof mainHomeLayoutTitleProductIdIndexLazyRoute;
	mainHomeLayoutSellerSellerIdIndexLazyRoute: typeof mainHomeLayoutSellerSellerIdIndexLazyRoute;
}

const mainHomeLayoutRouteChildren: mainHomeLayoutRouteChildren = {
	mainHomeLayoutIndexRoute: mainHomeLayoutIndexRoute,
	mainHomeLayoutprofileRoute: mainHomeLayoutprofileRouteWithChildren,
	mainHomeLayoutWishlistIndexRoute: mainHomeLayoutWishlistIndexRoute,
	mainHomeLayoutCartIndexLazyRoute: mainHomeLayoutCartIndexLazyRoute,
	mainHomeLayoutTitleProductIdIndexLazyRoute: mainHomeLayoutTitleProductIdIndexLazyRoute,
	mainHomeLayoutSellerSellerIdIndexLazyRoute: mainHomeLayoutSellerSellerIdIndexLazyRoute,
};

const mainHomeLayoutRouteWithChildren = mainHomeLayoutRoute._addFileChildren(mainHomeLayoutRouteChildren);

interface mainRouteChildren {
	mainHomeLayoutRoute: typeof mainHomeLayoutRouteWithChildren;
}

const mainRouteChildren: mainRouteChildren = {
	mainHomeLayoutRoute: mainHomeLayoutRouteWithChildren,
};

const mainRouteWithChildren = mainRoute._addFileChildren(mainRouteChildren);

export interface FileRoutesByFullPath {
	"/": typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren;
	"/partners": typeof dashboardPartnersIndexRoute;
	"/dashboard": typeof dashboardDashboardLayoutDashboardIndexRoute;
	"/wishlist": typeof mainHomeLayoutWishlistIndexRoute;
	"/cart": typeof mainHomeLayoutCartIndexLazyRoute;
	"/dashboard/orders": typeof dashboardDashboardLayoutDashboardOrdersIndexRoute;
	"/dashboard/products": typeof dashboardDashboardLayoutDashboardProductsIndexRoute;
	"/$title/$productId": typeof mainHomeLayoutTitleProductIdIndexLazyRoute;
	"/seller/$sellerId": typeof mainHomeLayoutSellerSellerIdIndexLazyRoute;
	"/dashboard/products/new": typeof dashboardDashboardLayoutDashboardProductsNewIndexRoute;
	"/addresses": typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute;
	"/orders": typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute;
	"/payments": typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute;
	"/profile": typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute;
	"/returns": typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute;
	"/security-settings": typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute;
	"/dashboard/products/edit/$productId": typeof dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute;
	"/orders/$orderId": typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute;
	"/orders/track/order/$orderId": typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute;
}

export interface FileRoutesByTo {
	"/": typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren;
	"/partners": typeof dashboardPartnersIndexRoute;
	"/dashboard": typeof dashboardDashboardLayoutDashboardIndexRoute;
	"/wishlist": typeof mainHomeLayoutWishlistIndexRoute;
	"/cart": typeof mainHomeLayoutCartIndexLazyRoute;
	"/dashboard/orders": typeof dashboardDashboardLayoutDashboardOrdersIndexRoute;
	"/dashboard/products": typeof dashboardDashboardLayoutDashboardProductsIndexRoute;
	"/$title/$productId": typeof mainHomeLayoutTitleProductIdIndexLazyRoute;
	"/seller/$sellerId": typeof mainHomeLayoutSellerSellerIdIndexLazyRoute;
	"/dashboard/products/new": typeof dashboardDashboardLayoutDashboardProductsNewIndexRoute;
	"/addresses": typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute;
	"/orders": typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute;
	"/payments": typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute;
	"/profile": typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute;
	"/returns": typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute;
	"/security-settings": typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute;
	"/dashboard/products/edit/$productId": typeof dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute;
	"/orders/$orderId": typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute;
	"/orders/track/order/$orderId": typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/(dashboard)": typeof dashboardRouteWithChildren;
	"/(dashboard)/_dashboardLayout": typeof dashboardDashboardLayoutRouteWithChildren;
	"/(main)": typeof mainRouteWithChildren;
	"/(main)/_homeLayout": typeof mainHomeLayoutRouteWithChildren;
	"/(dashboard)/partners/": typeof dashboardPartnersIndexRoute;
	"/(main)/_homeLayout/": typeof mainHomeLayoutIndexRoute;
	"/(main)/_homeLayout/(profile)": typeof mainHomeLayoutprofileRouteWithChildren;
	"/(main)/_homeLayout/(profile)/_profileLayout": typeof mainHomeLayoutprofileProfileLayoutRouteWithChildren;
	"/(dashboard)/_dashboardLayout/dashboard/": typeof dashboardDashboardLayoutDashboardIndexRoute;
	"/(main)/_homeLayout/wishlist/": typeof mainHomeLayoutWishlistIndexRoute;
	"/(main)/_homeLayout/cart/": typeof mainHomeLayoutCartIndexLazyRoute;
	"/(dashboard)/_dashboardLayout/dashboard/orders/": typeof dashboardDashboardLayoutDashboardOrdersIndexRoute;
	"/(dashboard)/_dashboardLayout/dashboard/products/": typeof dashboardDashboardLayoutDashboardProductsIndexRoute;
	"/(main)/_homeLayout/$title/$productId/": typeof mainHomeLayoutTitleProductIdIndexLazyRoute;
	"/(main)/_homeLayout/seller/$sellerId/": typeof mainHomeLayoutSellerSellerIdIndexLazyRoute;
	"/(dashboard)/_dashboardLayout/dashboard/products/new/": typeof dashboardDashboardLayoutDashboardProductsNewIndexRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/addresses/": typeof mainHomeLayoutprofileProfileLayoutAddressesIndexLazyRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/orders/": typeof mainHomeLayoutprofileProfileLayoutOrdersIndexLazyRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/payments/": typeof mainHomeLayoutprofileProfileLayoutPaymentsIndexLazyRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/profile/": typeof mainHomeLayoutprofileProfileLayoutProfileIndexLazyRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/returns/": typeof mainHomeLayoutprofileProfileLayoutReturnsIndexLazyRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/security-settings/": typeof mainHomeLayoutprofileProfileLayoutSecuritySettingsIndexLazyRoute;
	"/(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/": typeof dashboardDashboardLayoutDashboardProductsEditProductIdIndexRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/": typeof mainHomeLayoutprofileProfileLayoutOrdersOrderIdIndexLazyRoute;
	"/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/": typeof mainHomeLayoutprofileProfileLayoutOrdersTrackOrderOrderIdIndexLazyRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/partners"
		| "/dashboard"
		| "/wishlist"
		| "/cart"
		| "/dashboard/orders"
		| "/dashboard/products"
		| "/$title/$productId"
		| "/seller/$sellerId"
		| "/dashboard/products/new"
		| "/addresses"
		| "/orders"
		| "/payments"
		| "/profile"
		| "/returns"
		| "/security-settings"
		| "/dashboard/products/edit/$productId"
		| "/orders/$orderId"
		| "/orders/track/order/$orderId";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/partners"
		| "/dashboard"
		| "/wishlist"
		| "/cart"
		| "/dashboard/orders"
		| "/dashboard/products"
		| "/$title/$productId"
		| "/seller/$sellerId"
		| "/dashboard/products/new"
		| "/addresses"
		| "/orders"
		| "/payments"
		| "/profile"
		| "/returns"
		| "/security-settings"
		| "/dashboard/products/edit/$productId"
		| "/orders/$orderId"
		| "/orders/track/order/$orderId";
	id:
		| "__root__"
		| "/(dashboard)"
		| "/(dashboard)/_dashboardLayout"
		| "/(main)"
		| "/(main)/_homeLayout"
		| "/(dashboard)/partners/"
		| "/(main)/_homeLayout/"
		| "/(main)/_homeLayout/(profile)"
		| "/(main)/_homeLayout/(profile)/_profileLayout"
		| "/(dashboard)/_dashboardLayout/dashboard/"
		| "/(main)/_homeLayout/wishlist/"
		| "/(main)/_homeLayout/cart/"
		| "/(dashboard)/_dashboardLayout/dashboard/orders/"
		| "/(dashboard)/_dashboardLayout/dashboard/products/"
		| "/(main)/_homeLayout/$title/$productId/"
		| "/(main)/_homeLayout/seller/$sellerId/"
		| "/(dashboard)/_dashboardLayout/dashboard/products/new/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/addresses/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/orders/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/payments/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/profile/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/returns/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/security-settings/"
		| "/(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/"
		| "/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	dashboardRoute: typeof dashboardRouteWithChildren;
	mainRoute: typeof mainRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
	dashboardRoute: dashboardRouteWithChildren,
	mainRoute: mainRouteWithChildren,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(dashboard)",
        "/(main)"
      ]
    },
    "/(dashboard)": {
      "filePath": "(dashboard)",
      "children": [
        "/(dashboard)/_dashboardLayout",
        "/(dashboard)/partners/"
      ]
    },
    "/(dashboard)/_dashboardLayout": {
      "filePath": "(dashboard)/_dashboardLayout.tsx",
      "parent": "/(dashboard)",
      "children": [
        "/(dashboard)/_dashboardLayout/dashboard/",
        "/(dashboard)/_dashboardLayout/dashboard/orders/",
        "/(dashboard)/_dashboardLayout/dashboard/products/",
        "/(dashboard)/_dashboardLayout/dashboard/products/new/",
        "/(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/"
      ]
    },
    "/(main)": {
      "filePath": "(main)",
      "children": [
        "/(main)/_homeLayout"
      ]
    },
    "/(main)/_homeLayout": {
      "filePath": "(main)/_homeLayout.tsx",
      "parent": "/(main)",
      "children": [
        "/(main)/_homeLayout/",
        "/(main)/_homeLayout/(profile)",
        "/(main)/_homeLayout/wishlist/",
        "/(main)/_homeLayout/cart/",
        "/(main)/_homeLayout/$title/$productId/",
        "/(main)/_homeLayout/seller/$sellerId/"
      ]
    },
    "/(dashboard)/partners/": {
      "filePath": "(dashboard)/partners/index.tsx",
      "parent": "/(dashboard)"
    },
    "/(main)/_homeLayout/": {
      "filePath": "(main)/_homeLayout/index.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(main)/_homeLayout/(profile)": {
      "filePath": "(main)/_homeLayout/(profile)",
      "parent": "/(main)/_homeLayout",
      "children": [
        "/(main)/_homeLayout/(profile)/_profileLayout"
      ]
    },
    "/(main)/_homeLayout/(profile)/_profileLayout": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout.tsx",
      "parent": "/(main)/_homeLayout/(profile)",
      "children": [
        "/(main)/_homeLayout/(profile)/_profileLayout/addresses/",
        "/(main)/_homeLayout/(profile)/_profileLayout/orders/",
        "/(main)/_homeLayout/(profile)/_profileLayout/payments/",
        "/(main)/_homeLayout/(profile)/_profileLayout/profile/",
        "/(main)/_homeLayout/(profile)/_profileLayout/returns/",
        "/(main)/_homeLayout/(profile)/_profileLayout/security-settings/",
        "/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/",
        "/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/"
      ]
    },
    "/(dashboard)/_dashboardLayout/dashboard/": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/index.tsx",
      "parent": "/(dashboard)/_dashboardLayout"
    },
    "/(main)/_homeLayout/wishlist/": {
      "filePath": "(main)/_homeLayout/wishlist/index.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(main)/_homeLayout/cart/": {
      "filePath": "(main)/_homeLayout/cart/index.lazy.ts",
      "parent": "/(main)/_homeLayout"
    },
    "/(dashboard)/_dashboardLayout/dashboard/orders/": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/orders/index.tsx",
      "parent": "/(dashboard)/_dashboardLayout"
    },
    "/(dashboard)/_dashboardLayout/dashboard/products/": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/products/index.tsx",
      "parent": "/(dashboard)/_dashboardLayout"
    },
    "/(main)/_homeLayout/$title/$productId/": {
      "filePath": "(main)/_homeLayout/$title/$productId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(main)/_homeLayout/seller/$sellerId/": {
      "filePath": "(main)/_homeLayout/seller/$sellerId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout"
    },
    "/(dashboard)/_dashboardLayout/dashboard/products/new/": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/products/new/index.tsx",
      "parent": "/(dashboard)/_dashboardLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/addresses/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/addresses/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/orders/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/orders/index.lazy.ts",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/payments/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/payments/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/profile/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/profile/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/returns/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/returns/index.lazy.ts",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/security-settings/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/security-settings/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/products/edit/$productId/index.tsx",
      "parent": "/(dashboard)/_dashboardLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/orders/$orderId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    },
    "/(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/": {
      "filePath": "(main)/_homeLayout/(profile)/_profileLayout/orders/track/order/$orderId/index.lazy.tsx",
      "parent": "/(main)/_homeLayout/(profile)/_profileLayout"
    }
  }
}
ROUTE_MANIFEST_END */
