services:
  - type: web
    name: noon-php-api
    env: php
    rootDir: server
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
