#!/usr/bin/env sh
set -e

echo "🎛️ [husky] Starting pre-commit checks..."

cd client || exit 1

echo "🧪 Running ESLint..."
pnpm eslint ./src --ext .js,.ts,.jsx,.tsx --fix

echo "🔍 Checking for TypeScript errors..."
pnpm run type-check

echo "📌 Restaging changed files..."
git add ./src

echo "✅ Pre-commit checks complete."
