#!/usr/bin/env sh
set -e

echo "🎛️ [husky] Starting pre-commit checks..."

if ! command -v pnpm >/dev/null 2>&1; then
  echo "❌ 'pnpm' not found. Please install it."
  exit 1
fi

cd client || {
  echo "❌ Failed to cd into 'client'."
  exit 1
}

echo "🧪 Running Biome lint..."
pnpm biome lint --write ./src

echo "🎨 Formatting..."
pnpm biome format --write ./src

echo "🔍 Checking for TypeScript errors..."
if tsc --noEmit -p tsconfig.app.json && tsc --noEmit -p tsconfig.node.json; then
  echo "✅ No TypeScript errors found."
else
  echo "❌ Found TypeScript errors."
  exit 1
fi
echo "📌 Restaging changed files..."
git add ./src

echo "✅ Pre-commit checks complete."
